// Mocks generated by Mockito 5.4.6 from annotations
// in nanobot_dart/test/agent/subagent_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nanobot_dart/src/agent/agent_loop.dart' as _i5;
import 'package:nanobot_dart/src/agent/context_builder.dart' as _i4;
import 'package:nanobot_dart/src/agent/tool_registry.dart' as _i3;
import 'package:nanobot_dart/src/bus/events.dart' as _i7;
import 'package:nanobot_dart/src/providers/llm_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLlmProvider_0 extends _i1.SmartFake implements _i2.LlmProvider {
  _FakeLlmProvider_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToolRegistry_1 extends _i1.SmartFake implements _i3.ToolRegistry {
  _FakeToolRegistry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextBuilder_2 extends _i1.SmartFake
    implements _i4.ContextBuilder {
  _FakeContextBuilder_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAgentResponse_3 extends _i1.SmartFake implements _i5.AgentResponse {
  _FakeAgentResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AgentLoop].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgentLoop extends _i1.Mock implements _i5.AgentLoop {
  @override
  _i2.LlmProvider get provider => (super.noSuchMethod(
        Invocation.getter(#provider),
        returnValue: _FakeLlmProvider_0(
          this,
          Invocation.getter(#provider),
        ),
        returnValueForMissingStub: _FakeLlmProvider_0(
          this,
          Invocation.getter(#provider),
        ),
      ) as _i2.LlmProvider);

  @override
  _i3.ToolRegistry get tools => (super.noSuchMethod(
        Invocation.getter(#tools),
        returnValue: _FakeToolRegistry_1(
          this,
          Invocation.getter(#tools),
        ),
        returnValueForMissingStub: _FakeToolRegistry_1(
          this,
          Invocation.getter(#tools),
        ),
      ) as _i3.ToolRegistry);

  @override
  _i4.ContextBuilder get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeContextBuilder_2(
          this,
          Invocation.getter(#context),
        ),
        returnValueForMissingStub: _FakeContextBuilder_2(
          this,
          Invocation.getter(#context),
        ),
      ) as _i4.ContextBuilder);

  @override
  int get maxIterations => (super.noSuchMethod(
        Invocation.getter(#maxIterations),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  _i6.Future<_i5.AgentResponse> process(
    _i7.InboundMessage? message, {
    _i5.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #process,
          [message],
          {#cancellationToken: cancellationToken},
        ),
        returnValue: _i6.Future<_i5.AgentResponse>.value(_FakeAgentResponse_3(
          this,
          Invocation.method(
            #process,
            [message],
            {#cancellationToken: cancellationToken},
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i5.AgentResponse>.value(_FakeAgentResponse_3(
          this,
          Invocation.method(
            #process,
            [message],
            {#cancellationToken: cancellationToken},
          ),
        )),
      ) as _i6.Future<_i5.AgentResponse>);

  @override
  _i6.Stream<_i5.AgentEvent> processStream(
    _i7.InboundMessage? message, {
    _i5.CancellationToken? cancellationToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #processStream,
          [message],
          {#cancellationToken: cancellationToken},
        ),
        returnValue: _i6.Stream<_i5.AgentEvent>.empty(),
        returnValueForMissingStub: _i6.Stream<_i5.AgentEvent>.empty(),
      ) as _i6.Stream<_i5.AgentEvent>);
}
